### ISSUE TITLE
Build and Run incubator-celeborn on Java 17

### ISSUE THREAD

**Issue by jameswangchen** [apache/incubator-celeborn#1155]
Celeborn can not work when spark3.x  running in Java17.
![image](https://user-images.githubusercontent.com/21259595/211479143-a680f261-1984-42fe-83bb-8ccb2d7ae043.png)

**Comment by pan3793** [comment]
Java 17 CI is added in CELEBORN-738, please open sub-task in CELEBORN-737 if you encounter other issues about Java 17
