### ISSUE TITLE
[BUG] Syntax error in helm charts file: prometheus-podmonitor.yaml

### ISSUE THREAD

**Issue by every-breaking-wave** [apache/incubator-celeborn#1336]
### What is the bug(with logs or screenshots)?
charts/celeborn/templates/prometheus-podmonitor.yaml has two syntax errors that will be reported when installed directly using helm, as follows.
![image](https://user-images.githubusercontent.com/86960423/224647325-20755aff-e365-4a3a-81c7-d3cbae03b2b2.png)
and the reason is just an extra space.
![image](https://user-images.githubusercontent.com/86960423/224647760-f29bd05b-970a-45a2-a49c-21d5d40ebc41.png)
It's easy to fix, but I don't have a jira account until now.
(btw, I am curious why the bug is ignored in test while it is  important and easy to find)
### How to reproduce the bug?
Steps to reproduce the bug.
just use helm to deploy, you will get the error
/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by waitinfuture** [comment]
Hi @every-breaking-wave , thanks for your feedback, I've approved your jira request and you should received the welcome mail.
We have to admit that currently the UT coverage is relatively low, especially for k8s environment, that's one of the important things we need to improve.
