### ISSUE TITLE
[FEATURE]  support tez client

### ISSUE THREAD

**Issue by BsoBird** [apache/incubator-celeborn#1573]
### Is your feature request related to a problem? Please describe.
None.

### Describe the solution you'd like
There are still many users using HIVE ON TEZ, and we hope that celeborn will support TEZ client. This will bring the processing power of HIVE ON TEZ to a new level.

### Describe alternatives you've considered
None.

**Comment by waitinfuture** [comment]
Hi @BsoBird , thanks for your feedback, the community does plan to enhance Celeborn to support tez and mr. BTW, it'll be great if you can participate in the development.
