### ISSUE TITLE
[BUG] Shuffle read latency is too high when automatic Broadcastjoin is triggered

### ISSUE THREAD

**Issue by thomasg19930417** [apache/incubator-celeborn#1712]
**Env:**

spark 3.2.2
celeborn 0.2.1

Question desc:

   When spark3 spark.sql.adaptive.autoBroadcastJoinThreshold is turned on, it is found that when automatic Broadcastjoin is triggered, if spark.sql.shuffle.partitions is set relatively large at this time, the broadcast time will be longer

**Spark config:**

#Dynamic resource
spark.dynamicAllocation.enabled true
spark.dynamicAllocation.minExecutors 1
spark.dynamicAllocation.maxExecutors 500
spark.dynamicAllocation.initialExecutors  2
spark.dynamicAllocation.executorIdleTimeout 120

#Adaptive
spark.shuffle.minNumPartitionsToHighlyCompress 5000
spark.sql.adaptive.enabled         true
spark.sql.adaptive.coalescePartitions.enabled true
spark.sql.adaptive.skewedJoin.enabled true
spark.sql.adaptive.advisoryPartitionSizeInBytes 64M
spark.sql.adaptive.coalescePartitions.minPartitionSize  10M
spark.sql.adaptive.skewJoin.skewedPartitionFactor 2
spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes 128M
spark.sql.optimizer.dynamicPartitionPruning.enabled   false

#celeborn
spark.shuffle.service.enabled false
celeborn.shuffle.rangeReadFilter.enabled true
celeborn.shuffle.partitionSplit.mode hard
spark.shuffle.manager org.apache.spark.shuffle.celeborn.RssShuffleManager
spark.celeborn.master.endpoints  xxxxxx
spark.rss.push.data.replicate false
spark.rss.shuffle.writer.mode hash

# kyuubi
spark.sql.optimizer.insertRepartitionBeforeWrite.enabled true
spark.sql.optimizer.finalStageConfigIsolation.enabled true
spark.sql.finalStage.adaptive.advisoryPartitionSizeInBytes 256M
spark.sql.finalStage.adaptive.coalescePartitions.minPartitionSize 50M
spark.sql.extensions org.apache.kyuubi.sql.KyuubiSparkSQLExtension,org.apache.kyuubi.plugin.spark.authz.ranger.RangerSparkExtension

**reproduce sql**

set spark.sql.adaptive.autoBroadcastJoinThreshold=10M;
set spark.sql.autoBroadcastJoinThreshold=-1;
set spark.sql.shuffle.partitions=5000;

select  a.id from 
( select id from    range(1,10000) )  a
inner join 
(select id  from  range(1,100) )  b  on a.id=b.id

I found that this will be affected by the spark.sql.shuffle.partitions parameter. When the parameter is relatively large, the broadcast process will take longer

Test case:

when spark.sql.shuffle.partitions=10;
![image](https://github.com/apache/incubator-celeborn/assets/20243868/58b7bff2-a1e5-4278-8cee-c6216d5bc723)

when set spark.sql.shuffle.partitions=1000;
![image](https://github.com/apache/incubator-celeborn/assets/20243868/5a3b9d79-8a9e-4858-b950-7364ba1d61f2)

when set 5000
![image](https://github.com/apache/incubator-celeborn/assets/20243868/f205e223-0ff5-4934-99cc-597c8c29bfb3)

I didn't find this problem when I used the native spark3 built-in shuffle
![image](https://github.com/apache/incubator-celeborn/assets/20243868/12f4adfa-0b13-401a-a379-7dcf39e91255)

**Comment by thomasg19930417** [comment]
I think it should be caused by too many connections when the partition is too large. I also found a lot of connection creation process from the log as follows
![image](https://github.com/apache/incubator-celeborn/assets/20243868/cdfe62fc-92ee-4304-aeba-4f50aaed6564)

**Comment by thomasg19930417** [comment]
If the shuffle.partitions can be reduced, this problem can be solved, but in complex tasks, both large and small tasks exist. If the setting is too small, it is not very suitable for large tasks

**Comment by pan3793** [comment]
Does increasing `celeborn.network.timeout` help? The default values is 240s.
https://celeborn.apache.org/docs/0.2.1-incubating/configuration/#network

**Comment by wForget** [comment]
Is it caused by not disabling `spark.sql.adaptive.localShuffleReader.enabled`?

**Comment by waitinfuture** [comment]
> Is it caused by not disabling `spark.sql.adaptive.localShuffleReader.enabled`?

Right, @thomasg19930417 could you turn off ```spark.sql.adaptive.localShuffleReader.enabled``` and test again?

**Comment by thomasg19930417** [comment]
After testing, it is indeed caused by this parameter, thank you for your reply @pan3793 @wForget @waitinfuture

**Comment by waitinfuture** [comment]
> After testing, it is indeed caused by this parameter, thank you for your reply @pan3793 @wForget @waitinfuture

![image](https://github.com/apache/incubator-celeborn/assets/948245/324b5aa5-6139-40d0-8856-c269a052f4fb)
We do added comment about this config, maybe we should highlight it more :)

**Comment by thomasg19930417** [comment]
> > After testing, it is indeed caused by this parameter, thank you for your reply @pan3793 @wForget @waitinfuture
> 
> ![image](https://user-images.githubusercontent.com/948245/253241674-324b5aa5-6139-40d0-8856-c269a052f4fb.png) We do added comment about this config, maybe we should highlight it more :)

This parameter was commented out by my mistake, maybe it was automatically commented out when the shell was copied.
