### ISSUE TITLE
[FEATURE] support create multiple celeborn clusters(for flink) in one kubernetes namespace

### ISSUE THREAD

**Issue by mddxhj** [apache/incubator-celeborn#1762]
### Is your feature request related to a problem? Please describe.
Currently, we can create only one celeborn cluster for flink when deploying on K8S in one namespace. In some scenarios, this is not very convenient. Supposing we have two resource pools divided by business type in the same k8s namespace，we have no way to create a celeborn cluster for both of the two resource pools.

### Describe the solution you'd like
For each celeborn cluster, we introduce a single values.yaml file that contains all the necessary configs for creating it, and we can create the cluster using the following helm command

```
helm install cluster1-celeborn --values cluster1_values.yaml .
helm install cluster2-celeborn --values cluster2_values.yaml .
```

and we can retrieve k8s pods of each celeborn  cluster by using
```
kubectl get po -l app.kubernetes.io/instance=cluster1-celeborn
kubectl get po -l app.kubernetes.io/instance=cluster2-celeborn
```

### Describe alternatives you've considered
None

**Comment by zwangsheng** [comment]
Hi @mddxhj, had raised a [PR](https://github.com/apache/incubator-celeborn/pull/1804) 
 to accomplish this goal.

You can code review whether it meets your expectations, if you have time.
