### ISSUE TITLE
[FEATURE] introduce jemalloc to optimize memory usage

### ISSUE THREAD

**Issue by mddxhj** [apache/incubator-celeborn#1823]
### Is your feature request related to a problem? Please describe.
I found after introducing jemalloc celeborn gains a better memory usage when deploying for flink on k8s.

### Describe the solution you'd like
Introduce jemalloc for celeborn

**Comment by waitinfuture** [comment]
Hi @mddxhj , thanks for your input! BTW, are you interested in raising a PR for this?

**Comment by mddxhj** [comment]
@waitinfuture yes，I'll raise a pr for this feature

**Comment by waitinfuture** [comment]
> @waitinfuture yes，I'll raise a pr for this feature

That's great!

**Comment by pan3793** [comment]
> ... gains a better memory usage ...

Could you share more information like metrics to prove such improvements?

**Comment by mddxhj** [comment]
> 

I have a case in our production environment, single pod work_set usage decreased from 9.3GB to 6GB approximately after enable jemalloc. see [CELEBORN-900](https://issues.apache.org/jira/browse/CELEBORN-900)

**Comment by pan3793** [comment]
@mddxhj the metrics of Pod memory looks nice! Have you observed differences between Netty memory / CPU usage on the Celeborn Grafana Dashboard?
