### ISSUE TITLE
[FEATURE] HDFS storage  support  NameNode HA  config

### ISSUE THREAD

**Issue by zhengshubin** [apache/incubator-celeborn#1846]
### Is your feature request related to a problem? Please describe.
I have a hadoop cluster with  namemode ha ,but  it make  errror when I  use  namenode ha config. 

### Describe the solution you'd like
HDFS storage  support  NameNode HA  config 
### Describe alternatives you've considered
Like doris hdfs ha config :
        "dfs.nameservices" = "my_hdfs",
            "dfs.ha.namenodes.my_hdfs" = "nn1,nn2",
            "dfs.namenode.rpc-address.my_hdfs.nn1" = "nanmenode01:8020",
            "dfs.namenode.rpc-address.my_hdfs.nn2" = "nanmenode02:8020",
            "dfs.client.failover.proxy.provider.my_hdfs" = "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider")
or  put the hdfs-site.xml to config path  and read it automatically.
/cc @who-need-to-know

/assign @who-can-help-you

**Comment by waitinfuture** [comment]
Hi @zhengshubin , you can pass hadoop related configs using `celeborn.hadoop.xxx`
