### ISSUE TITLE
[DOC] Update Configuration for spark.shuffle.sort.io.plugin.class

### ISSUE THREAD

**Issue by a140262** [apache/incubator-celeborn#1899]
### Describe the intention you'd like
Starting from Spark 3.5, it will support Celeborn natively without patching Spark code. User just need to set `spark.shuffle.sort.io.plugin.class` to `org.apache.spark.shuffle.celeborn.CelebornShuffleDataIO` to enable this new feature.  Please update the documentation accordingly. Please refer to [CELEBORN-913](https://issues.apache.org/jira/browse/CELEBORN-913) & [SPARK-42689](https://github.com/apache/spark/pull/40307)

**Comment by pan3793** [comment]
Already tracked via CELEBORN-954, please open JIRA instead of GitHub issue to report issues.
