### ISSUE TITLE
[Suggestion] Startup master/worker listen on 0.0.0.0 by default

### ISSUE THREAD

**Issue by xleoken** [apache/incubator-celeborn#1991]
### Is your feature request related to a problem? Please describe.

When the master/worker started, it will listen on a specific ip. It's not friendly when deploy these components on server with multiple networks.

### Describe alternatives you've considered
It seems better to let master/worker to listen on `0.0.0.0` by defalt.

### Other
Please share your idea about this topic 😃

**Comment by waitinfuture** [comment]
Hi @xleoken , thanks for raising this discussion! IMO it's fine for workers to listen on `0.0.0.0`, but since Master's ip:port is used by Workers and Clients, I think we can't let Master use `0.0.0.0`.

**Comment by xleoken** [comment]
Thanks @waitinfuture

**Comment by pan3793** [comment]
@xleoken the current behavior is to listen to the first non-loopback address if not explicitly configured, 0.0.0.0 is not a good candidate as the fallback behavior IMO, for both security purposes and service discovery mechanism.

PS: Better to use mailing list or GitHub discussion for starting such a conversation.
