### ISSUE TITLE
[FEATURE] make affinity.master and affinity.worker optional

### ISSUE THREAD

**Issue by doki23** [apache/incubator-celeborn#2066]
### Is your feature request related to a problem? Please describe.
I set `affinity` to `None` and got an error: 
```
Error: INSTALLATION FAILED: template: celeborn/templates/worker-statefulset.yaml:54:22: executing "celeborn/templates/worker-statefulset.yaml" at <.Values.affinity.worker>: nil pointer evaluating interface {}.worker
```
It seems that we must provide a key of `affinity.worker` in the `values.yaml` ?

### Describe the solution you'd like
make affinity.master and affinity.worker optional

**Comment by shohamy7** [comment]
Hi!
I would like to fix this :)

**Comment by hemu-git-hub** [comment]
@doki23 can I work on this issue ?

**Comment by doki23** [comment]
@hemu-git-hub Feel free to do this.
