### ISSUE TITLE
[BUG] master cannot startup

### ISSUE THREAD

**Issue by doki23** [apache/incubator-celeborn#2067]
### What is the bug(with logs or screenshots)?
Here are logs of master:
<img width="634" alt="截屏2023-11-03 10 21 09" src="https://github.com/apache/incubator-celeborn/assets/11144133/132f9453-2198-400f-9707-4f53e03e27dd">
It also happens on worker.

### How to reproduce the bug?
Remove the `affinity` values(should have no affection).
Launch it by helm in my macbook pro m1 and it occurs.
The image is `aliyunemr/remote-shuffle-service:0.1.1-6badd20`.

**Comment by mircode** [comment]
需要重新打一个新的镜像，配置文件的镜像仅是一个例子
