### ISSUE TITLE
[FEATURE] Set resources ( cpu/memory requests and limits) for initContainers for Helm chart

### ISSUE THREAD

**Issue by marwansalem** [apache/incubator-celeborn#2094]
### Is your feature request related to a problem? Please describe.
Worker and Master Pods did not start when installing helm chart into a namespace with resource quota.

### Describe the solution you'd like
Use the same resources values as  "main" container resources.
This requires modifying `master-statefulset` and `worker-statefulset` 

### Describe alternatives you've considered

/cc @who-need-to-know

/assign @who-can-help-you

[PR
](https://github.com/apache/incubator-celeborn/pull/2093)

**Comment by SteNicholas** [comment]
@pan3793, this issue could be closed.

**Comment by pan3793** [comment]
close as completed
