### ISSUE TITLE
Please add tag for 0.4.0 version

### ISSUE THREAD

**Issue by donan92** [apache/incubator-celeborn#2295]
Hi admin, Celeborn v0.4.0 has been released from 4th Feb, but in this repo, there is no tags for v0.4.0.
Could you add a new tag for v0.4.0?

https://celeborn.apache.org/community/release_notes/release_note_0.4.0/

**Comment by turboFei** [comment]
See [v0.4.0-incubating](https://github.com/apache/incubator-celeborn/tree/v0.4.0-incubating)

**Comment by donan92** [comment]
ah! I confused "release" to "tag" 😀

**Comment by donan92** [comment]
Hi @pan3793, it still has not made a release of v0.4.0-incubating, is it intent?
The latest release is v0.3.2-incubating yet.
![image](https://github.com/apache/incubator-celeborn/assets/70442029/1f971d67-2b53-4c90-964f-9dd73967a5c8)
