### ISSUE TITLE
The network bandwidth is full, causing a timeout 【k8s】

### ISSUE THREAD

**Issue by liugs0213** [apache/incubator-celeborn#286]
### Is your feature request related to a problem? Please describe.
The RSS service is deployed on K8S. When there is a large amount of work, the network adapter bandwidth of the machine is full, resulting in batch failure, and the network bandwidth is 20Gb/s
![image](https://user-images.githubusercontent.com/55676558/181216289-c2e0f2c7-bee8-4668-af66-3461d9018cb1.png)

### Describe the solution you'd like
want to add flow limiting

### Describe alternatives you've considered

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by FMX** [comment]
@liugs0213 Hi,  you are welcome to discuss more details about this question at gitter(https://gitter.im/RemoteShuffleServiceCommunity/community).

**Comment by waitinfuture** [comment]
Currently RSS‘ traffic control is based on memory pressure, I think it's reasonable to also consider bandwidth.

**Comment by liugs0213** [comment]
> @liugs0213 Hi, you are welcome to discuss more details about this question at gitter(https://gitter.im/RemoteShuffleServiceCommunity/community).

ok好的
