### ISSUE TITLE
[BUG] The node IP cannot be obtained correctly when deploying the okd cluster node

### ISSUE THREAD

**Issue by lukeyan2023** [apache/incubator-celeborn#438]
### What is the bug(with logs or screenshots)?

When RSS is deployed on the node of the okd cluster, the node IP cannot be obtained correctly after the master is started

### How to reproduce the bug?

Prerequisite: a deployed okd cluster, version 4.10
1.Select the node of the okd cluster as the RSS deployment environment, configure it according to the official guidelines, and then start the RSS master
2. Use netstat - tuanp to view the port monitored by the master. You will find that the monitored IP is not the node IP

Could you share logs or screenshots?

![19c60310bd2a77840dfead870f3d5b1](https://user-images.githubusercontent.com/108530647/186108263-e7fc8d9d-89a6-4935-8a15-37ef0d769bac.png)

![0a8415055229d201d8772c8bbe88c3c](https://user-images.githubusercontent.com/108530647/186108561-4ba273aa-7d66-429d-b94f-4ad6f18c319f.png)

**Comment by waitinfuture** [comment]
rss.master.address is for client，you can try --host xxx，or set environment variable RSS_MASTER_HOST to bind host when start master
