### ISSUE TITLE
[REFACTOR] Unify control messages

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-celeborn#673]
### Describe the intention you'd like

Currently, there are three control message systems in the project:

1. `common/proto/TransportMessages.proto`, defined in proto3 syntax, used for client/server rpc serialization
2. `com.aliyun.emr.rss.common.protocol.message.Message` and subclasses, scala case class wrapper for 1
3. `server-master/proto/Resource.proto`, defined in proto2 syntax, used for master ratis rpc serialization

Three control message systems introduce redundant transformation and make the code complex, so I propose to drop 2 and 3, and unify all control messages to 1.

In detail, I'm going to remove 2 first, the refactoring should be safe since it does not use for serialization.

And then, replace 3 w/ 1, but keep the decode be compatibility w/ 3, because 3 is used for serialization.

Finally, remove 3 totally after the next release.

### Sub tasks

- #678
- #680
- #716
- #718
- #719
- #720

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by waitinfuture** [comment]
This work is important, thanks!
