### ISSUE TITLE
[Improvement] Generate patch to each Spark minor version

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-celeborn#858]
### Describe the intention you'd like

The current Spark3 DRA patch is based on a version nearby Spark 3.2.2, some conflict will occur if we apply it to Spark 3.1.3 or Spark 3.3.1.

We should generate the patch for each Spark minor version(latest patch version), to make sure the user can apply the patch easily.

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by ishu-thakur** [comment]
Hi @pan3793 I would like to contribute but before that i want to ask abit more information about requirement as do we have to make a patch Api ? and how the URL would look like and what are the field we can update while doing patch :)

**Comment by pan3793** [comment]
Hi @ishu-thakur, it's not something about HTTP. The "patch" means https://github.com/alibaba/celeborn/tree/main/assets/spark-patch

**Comment by lukeyan2023** [comment]
@pan3793 I can contribute this，please assign to me thank you

**Comment by pan3793** [comment]
@lukeyan2023 assigned. Go head, please

**Comment by pan3793** [comment]
Spark use semantic version `<major>.<minor>.<patch>`.

I suppose we should generate the patch for each latest minor version of Spark, and verify they could be applied to all corresponding patch versions without conflicts.

**Comment by lukeyan2023** [comment]
@pan3793 I have submitted a related PR but I don’t know how to link it to this issue
