### ISSUE TITLE
[IMPROVEMENT] Get chunkSize from server instead of from conf

### ISSUE THREAD

**Issue by waitinfuture** [apache/incubator-celeborn#862]
### Is your feature request related to a problem? Please describe.
Currently DfsPartitionReader gets shuffleChunkSize from client-side configuration
```
    shuffleChunkSize = (int) conf.shuffleChunkSize();
```
However it may happen that client-side config is not consistent with server-side config. We should get this config from server, possibly returned through GetReducerFileGroupResponse, like the following
```
  case class GetReducerFileGroupResponse(
      status: StatusCode,
      fileGroup: Array[Array[PartitionLocation]],
      attempts: Array[Int],
      shuffleChunkSize: Int)
```

### Describe alternatives you've considered

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by tobehardest** [comment]
Or maybe I can try it, can you assign it to me?

**Comment by waitinfuture** [comment]
> Or maybe I can try it, can you assign it to me?

Sure, assigned, thanks! BTW, do you have a jira account? Currently Celeborn uses jira for issue tracking, I'd like to create an issue there and assign to you.

**Comment by waitinfuture** [comment]
> Or maybe I can try it, can you assign it to me?

@tobehardest https://issues.apache.org/jira/browse/CELEBORN-498

**Comment by tobehardest** [comment]
> > Or maybe I can try it, can you assign it to me?
> 
> Sure, assigned, thanks! BTW, do you have a jira account? Currently Celeborn uses jira for issue tracking, I'd like to create an issue there and assign to you.

Oh, I don't have a jira account yet, I'm new here, and the system tells me that I need to contact the administrator to apply for an account.

**Comment by waitinfuture** [comment]
> 

You can request jira account here:

**Comment by tobehardest** [comment]
> > 
> 
> @tobehardest You can request jira account here: https://selfserve.apache.org/jira-account.html and select "Celeborn"

ok, done.

**Comment by waitinfuture** [comment]
> 

Approved, you should've received the welcome email. You can assign the issue to yourself, thanks for contributing~

**Comment by lishiyucn** [comment]
Only the "celeborn.shuffle.chunk.size" param take value from server-side config?

**Comment by waitinfuture** [comment]
> @waitinfuture Only the "celeborn.shuffle.chunk.size" param take value from server-side config?

@lishiyucn I'm not sure whether there are other configs that should use server-side config, but for this one it really should use server-side config rather than client-side. And we should change the categories of this config to `worker` only.

**Comment by lishiyucn** [comment]
I have fixed the issue, please assign it to me, Thanks.

**Comment by waitinfuture** [comment]
> I have fixed the issue, please assign it to me, Thanks.

done
