### ISSUE TITLE
server can't find celeborn-master-1.celeborn-master-svc: NXDOMAIN

### ISSUE THREAD

**Issue by bigdata-spec** [apache/incubator-celeborn#886]
Hello，I want to  consult about RSS on K8s.
when I run **helm install celeborn-helm helm -n rss** 

```
** server can't find celeborn-master-1.celeborn-master-svc: NXDOMAIN

waiting for master
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   celeborn-master-0.celeborn-master-svc.rss.svc.cluster.local
Address: 10.244.236.151

Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find celeborn-master-1.celeborn-master-svc: NXDOMAIN

waiting for master
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   celeborn-master-0.celeborn-master-svc.rss.svc.cluster.local
Address: 10.244.236.151

Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find celeborn-master-1.celeborn-master-svc: NXDOMAIN
```
![image](https://user-images.githubusercontent.com/23710717/198537436-43896afa-0c34-4534-b1ab-cd8b8a3abf13.png)

**Comment by pan3793** [comment]
Your pasted log will be printed until all master nodes are launched, then the issue here is why `celeborn-master-1` and `celeborn-master-2` pods launch failed.

**Comment by jiangbiao910** [comment]
> Your pasted log will be printed until all master nodes are launched, then the issue here is why `celeborn-master-1` and `celeborn-master-2` pods launch failed.

you are right,do you kown why `celeborn-master-1` and `celeborn-master-2` pods launch failed? Maybe network?

**Comment by pan3793** [comment]
Are there logs on the failed Pod?
