### ISSUE TITLE
[Umbrella] Celeborn Support Apache Flink

### ISSUE THREAD

**Issue by RexXiong** [apache/incubator-celeborn#904]
### Abstract
Apache Flink is not currently supported by Celeborn. It makes sense to make Celeborn to support Apache Flink in batch scenarios as Spark，Flink or Other engine shuffle process don't need two separate shuffle clusters. At the same time Flink shuffle process will benefit from the many features provided by Celeborn.

### Features
- [ ] #946
- [ ] #945
- [x] #949
- [ ] #947
- [ ] Flink Shuffle plugin of Celeborn

### Design Doc
 coming soon

/cc @FMX 

/assign @who-can-help-you

**Comment by czy006** [comment]
Now there is a [flink-remote-shuffle](https://github.com/flink-extended/flink-remote-shuffle) project in apache flink community. I think this part of function can be transplanted here based on 1.16. If there is a plan for this part, I think it is very good and I am willing to assist in this work

**Comment by FMX** [comment]
@czy006 You are welcome to participate. The design doc will be available soon. We had lots of negotiations with the developers of the flink-remote-shuffle project and we'll support flink. Our goal is to support flink 1.13 and newer versions.

**Comment by zhisheng17** [comment]
If we want to add support for Flink 1.16 to Celeborn's current codebase, what modifications need to be made? Why flink 1.16 version is not currently supported? 

<img width="891" alt="image" src="https://github.com/apache/celeborn/assets/10086212/58332898-c66a-4e99-a0f3-753b14715234">

**Comment by RexXiong** [comment]
> If we want to add support for Flink 1.16 to Celeborn's current codebase, what modifications need to be made? Why flink 1.16 version is not currently supported?
> 
Support for different versions of the Flink is based on community needs, and integrate with Flink1.16 is not much different from other versions. Pls go ahead and create a JIRA ticket for supporting Flink 1.16.
