### ISSUE TITLE
[IMPROVEMENT] Decrease celeborn.<module>.io.numConnectionsPerPeer default value to avoid too many network connections

### ISSUE THREAD

**Issue by waitinfuture** [apache/incubator-celeborn#911]
### Describe the intention you'd like
A clear and concise description of what you want to do.

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by FMX** [comment]
I have done some tests about the effect of num connection per peer. I run the terasort with a data scale of 150GB on 4 nodes.
I get the result:
if numConnectionsPerPeer is 1, shuffle write will cost 57s.
if numConnectionsPerPeer is 2, shuffle write will cost 52s.
if numConnectionsPerPeer is 8, shuffle write will cost 51s.

So let us set the default value to 2.
